### ISSUE TITLE
Processing uploaded video from client-side upload

### ISSUE THREAD

**Issue by joeytheman** [shrinerb/shrine-cloudinary#3]
I am using the Cloudinary gem and the instructions at
https://cloudinary.com/documentation/rails_video_upload#example_2_client_side_upload_from_the_browser_signed_upload 
to achieve client-side uploading. Once the video is uploaded, the following is passed to the `video` params
 ```` 
 video/upload/v1521075899/dhdb42d8mjwkckupbuwa.mov#407dfca70490b670129337ba93a09a9c76930c65
````
Cloudinary recommends processing images using https://cloudinary.com/documentation/rails_image_upload#direct_upload_file_tag

which results in

    <Cloudinary::PreloadedFile:0x00007f9dab0f9308 @resource_type="video", @type="upload", @version="1521075899", @filename="dhdb42d8mjwkckupbuwa.mov", @signature="407dfca70490b670129337ba93a09a9c76930c65", @public_id="dhdb42d8mjwkckupbuwa", @format="mov">

I came up with
````
  def process_direct_upload(cloudinary_video_url)
    preloaded_file = Cloudinary::PreloadedFile.new(cloudinary_video_url)
    storage, filename = preloaded_file.filename.split('/')
    shrine_uploaded_file_options = {
      'id' => preloaded_file.identifier.split('/').last,
      'storage' => storage,
      'metadata' => {
        'filename' => filename
      }
    }

    VideoUploader::UploadedFile.new shrine_uploaded_file_options
  end
````
but when I set the video as such
 ````
object.video = process_direct_upload(params[:object][:video])
````
it re-uploads the video when the record is saved.

What is the best way to process the client-side upload?

**Comment by janko-m** [comment]
Nice, you've already done most of the work.

The reason the video gets re-uploaded is because when you use regular assignment, `Shrine::Attacher#assign` that gets called treats whatever you give it as an IO object which it needs to attach, regardless of whether it's a `Shrine::UploadedFile` instance.

What you want is to use `Shrine::Attacher#set`, which attaches a `Shrine::UploadedFile` object as is (and automatically promotes it on save if it's from a temporary storage):

```rb
object.video_attacher.set process_direct_upload(params[:object][:video])
```

**Comment by joeytheman** [comment]
Using the code you supplied, the video attached without having to re-upload as expected but it is not promoted from temporary storage. 

My initializer is configured as follows
````
Cloudinary.config(opts)

Shrine.storages = {
  cache: Shrine::Storage::Cloudinary.new(prefix: "cache", resource_type: 'video'), # for direct uploads
  store: Shrine::Storage::Cloudinary.new(prefix: "store", resource_type: 'video')
}

Shrine.plugin :determine_mime_type
Shrine.plugin :cached_attachment_data

````

Any suggestions?

**Comment by janko-m** [comment]
Did you load the ORM plugin (`activerecord`)?

**Comment by joeytheman** [comment]
I added the ORM plugin and that fixed it. 

Thanks for your help and the gem!!!
