### ISSUE TITLE
`open` method doesn't account for signed URLs

### ISSUE THREAD

**Issue by kimili** [shrinerb/shrine-cloudinary#4]
I'm uploading video assets to directly to Cloudinary (using Uppy and the `presign_endpoint` plugin). The assets are getting there no problem.

However, I want to restrict access to the original source file on Cloudinary, so I have tried setting upload `type` set to `private` or `authenticated`, or the `access_mode` to `authenticated`. This scenario sets up a failure retrieving metadata from the source file.

<img width="1611" alt="screenshot 2018-12-21 00 30 03" src="https://user-images.githubusercontent.com/351819/50326293-93ff0200-04b7-11e9-86fd-da28785bd14f.png">

As you can see from the call stack in the screenshot, it's calling `refresh_metadata` which eventually makes its way to the `open` method in the `Shrine::Storage::Cloudinary` class. That method has no way to call Cloudinary signed URLs as far as I can tell. In this case, if the `open` method used the `sign_url` parameter:

```ruby
def open(**options)
  Down::Http.open(url(id, sign_url: true), **options)
end
```

...the request is authenticated and completes successfully. Any suggestions as to how I can work around this?

**Comment by janko-m** [comment]
Thanks a lot for the detailed report and finding the solution. Since `sign_url: true` will work for public uploads as well, I don't see any reason why it shouldn't be the default. I will push a fix and release 1.0.1.
